// GENERATED by scripts/gen-api-dispatch.mjs — do not edit. Run `node scripts/gen-api-dispatch.mjs --write`.
// One route for every endpoint under /api/portal/[saId]; handlers live in ../_routes/.
import "server-only";

import { createApiDispatcher } from "@/lib/server/api-dispatch";
import * as h0 from "@/app/api/portal/[saId]/_routes/billing/portal/route";
import * as h1 from "@/app/api/portal/[saId]/_routes/login/route";
import * as h2 from "@/app/api/portal/[saId]/_routes/login/verify/route";
import * as h3 from "@/app/api/portal/[saId]/_routes/logout/route";
import * as h4 from "@/app/api/portal/[saId]/_routes/projects/[projectId]/route";
import * as h5 from "@/app/api/portal/[saId]/_routes/projects/[projectId]/steps/[stepId]/route";
import * as h6 from "@/app/api/portal/[saId]/_routes/projects/[projectId]/steps/route";
import * as h7 from "@/app/api/portal/[saId]/_routes/projects/[projectId]/tasks/route";
import * as h8 from "@/app/api/portal/[saId]/_routes/projects/route";
import * as h9 from "@/app/api/portal/[saId]/_routes/quotes/[quoteId]/view/route";
import * as h10 from "@/app/api/portal/[saId]/_routes/tasks/[taskId]/route";
import * as h11 from "@/app/api/portal/[saId]/_routes/time/entries/[entryId]/route";
import * as h12 from "@/app/api/portal/[saId]/_routes/time/entries/route";
import * as h13 from "@/app/api/portal/[saId]/_routes/time/timer/route";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const d = createApiDispatcher([
  ["billing/portal", h0],
  ["login", h1],
  ["login/verify", h2],
  ["logout", h3],
  ["projects/[projectId]", h4],
  ["projects/[projectId]/steps/[stepId]", h5],
  ["projects/[projectId]/steps", h6],
  ["projects/[projectId]/tasks", h7],
  ["projects", h8],
  ["quotes/[quoteId]/view", h9],
  ["tasks/[taskId]", h10],
  ["time/entries/[entryId]", h11],
  ["time/entries", h12],
  ["time/timer", h13],
]);

export const GET = d.GET;
export const HEAD = d.HEAD;
export const POST = d.POST;
export const PUT = d.PUT;
export const PATCH = d.PATCH;
export const DELETE = d.DELETE;
export const OPTIONS = d.OPTIONS;
