import "server-only";

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { AiSuiteKnowledgeCard, AiSuiteLevel } from "@/types/ai-suite";

/**
 * Programmatic editing of the AI Suite knowledge base — used by the
 * local-dev-only "Review knowledge base" button in Agency Settings.
 *
 * Safety model: the LLM only ever proposes card DATA (validated against the
 * schema below); the TypeScript file is regenerated by `serializeKnowledgeBase`
 * from validated objects. The model never emits code, so a hallucinated
 * bracket can't break the build. The write targets the source tree, which
 * only exists when running `pnpm dev` locally — the routes enforce that.
 */

export const KB_FILE_PATH = resolve(
  process.cwd(),
  "src/lib/ai-suite/knowledge-base.ts",
);

export interface KbChange {
  op: "add" | "update" | "delete";
  /** Card id the change targets. */
  id: string;
  /** One-line human reason, shown in the review dialog. */
  reason: string;
  /** Full card for add/update. */
  card?: AiSuiteKnowledgeCard;
}

const ID_RE = /^[a-z0-9-]+$/;
const LEVELS = new Set<AiSuiteLevel>(["agency", "sub-account"]);

/** Validate one card shape. Returns an error string, or null when valid. */
export function validateKbCard(raw: unknown): string | null {
  if (!raw || typeof raw !== "object") return "card must be an object";
  const c = raw as Record<string, unknown>;
  if (typeof c.id !== "string" || !ID_RE.test(c.id)) {
    return "card id must be kebab-case (a-z, 0-9, dashes)";
  }
  if (
    !Array.isArray(c.levels) ||
    c.levels.length === 0 ||
    !c.levels.every((l) => LEVELS.has(l as AiSuiteLevel))
  ) {
    return `card ${c.id}: levels must be a non-empty array of "agency" | "sub-account"`;
  }
  for (const key of ["title", "location", "body"] as const) {
    if (typeof c[key] !== "string" || !(c[key] as string).trim()) {
      return `card ${c.id}: ${key} is required`;
    }
  }
  if ((c.body as string).length > 2000) {
    return `card ${c.id}: body too long (2000 chars max)`;
  }
  if (
    !Array.isArray(c.keywords) ||
    c.keywords.length === 0 ||
    c.keywords.length > 15 ||
    !c.keywords.every((k) => typeof k === "string" && k.trim())
  ) {
    return `card ${c.id}: keywords must be 1-15 non-empty strings`;
  }
  return null;
}

/** Normalize a validated card to exactly the persisted shape. */
function normalizeCard(raw: AiSuiteKnowledgeCard): AiSuiteKnowledgeCard {
  return {
    id: raw.id.trim(),
    levels: [...new Set(raw.levels)] as AiSuiteLevel[],
    title: raw.title.trim(),
    location: raw.location.trim(),
    keywords: raw.keywords.map((k) => k.trim().toLowerCase()),
    body: raw.body.trim(),
  };
}

/** Validate a change list against the current cards. Throws Error on any problem. */
export function validateKbChanges(
  current: AiSuiteKnowledgeCard[],
  rawChanges: unknown,
): KbChange[] {
  if (!Array.isArray(rawChanges)) throw new Error("changes must be an array");
  const ids = new Set(current.map((c) => c.id));
  const seen = new Set<string>();
  const changes: KbChange[] = [];
  for (const raw of rawChanges) {
    if (!raw || typeof raw !== "object") throw new Error("each change must be an object");
    const ch = raw as Record<string, unknown>;
    const op = ch.op;
    if (op !== "add" && op !== "update" && op !== "delete") {
      throw new Error(`unknown op '${String(op)}'`);
    }
    const id = typeof ch.id === "string" ? ch.id.trim() : "";
    if (!id) throw new Error("each change needs the target card id");
    if (seen.has(id)) throw new Error(`duplicate change for card '${id}'`);
    seen.add(id);
    const reason =
      typeof ch.reason === "string" ? ch.reason.trim().slice(0, 300) : "";

    if (op === "delete") {
      if (!ids.has(id)) throw new Error(`can't delete unknown card '${id}'`);
      changes.push({ op, id, reason });
      continue;
    }
    const cardError = validateKbCard(ch.card);
    if (cardError) throw new Error(cardError);
    const card = normalizeCard(ch.card as AiSuiteKnowledgeCard);
    if (card.id !== id) throw new Error(`change id '${id}' doesn't match card id '${card.id}'`);
    if (op === "add" && ids.has(id)) throw new Error(`card '${id}' already exists — use update`);
    if (op === "update" && !ids.has(id)) throw new Error(`can't update unknown card '${id}' — use add`);
    changes.push({ op, id, reason, card });
  }
  return changes;
}

/** Apply validated changes: updates in place, deletes removed, adds appended. */
export function applyKbChanges(
  current: AiSuiteKnowledgeCard[],
  changes: KbChange[],
): AiSuiteKnowledgeCard[] {
  const deletes = new Set(
    changes.filter((c) => c.op === "delete").map((c) => c.id),
  );
  const updates = new Map(
    changes.filter((c) => c.op === "update").map((c) => [c.id, c.card!]),
  );
  const adds = changes.filter((c) => c.op === "add").map((c) => c.card!);
  return [
    ...current
      .filter((c) => !deletes.has(c.id))
      .map((c) => updates.get(c.id) ?? c),
    ...adds,
  ];
}

const S = (v: string) => JSON.stringify(v);

/** Regenerate the knowledge-base.ts source from validated card objects. */
export function serializeKnowledgeBase(cards: AiSuiteKnowledgeCard[]): string {
  const cardBlocks = cards.map((c) =>
    [
      "  {",
      `    id: ${S(c.id)},`,
      `    levels: [${c.levels.map(S).join(", ")}],`,
      `    title: ${S(c.title)},`,
      `    location: ${S(c.location)},`,
      `    keywords: [${c.keywords.map(S).join(", ")}],`,
      `    body:`,
      `      ${S(c.body)},`,
      "  },",
    ].join("\n"),
  );
  return [
    `import type { AiSuiteKnowledgeCard } from "@/types/ai-suite";`,
    ``,
    `/**`,
    ` * The AI Suite knowledge base.`,
    ` *`,
    ` * Each card is one feature's how-to, grounded in how the app actually`,
    ` * behaves. The \`title\` + \`location\` are aligned to the real sidebar nav and`,
    ` * route tree; the \`body\` is the authoritative content the assistant is`,
    ` * allowed to state.`,
    ` *`,
    ` * Maintained two ways (both regenerate this file deterministically from`,
    ` * validated card data — edit cards, not formatting):`,
    ` *   - the \`/update-ai-kb\` Claude Code skill (deep, code-aware review)`,
    ` *   - Agency Settings → AI knowledge (local dev only — quick LLM-assisted`,
    ` *     refresh with card-by-card approval)`,
    ` */`,
    `export const AI_SUITE_KNOWLEDGE: AiSuiteKnowledgeCard[] = [`,
    cardBlocks.join("\n"),
    `];`,
    ``,
  ].join("\n");
}

/** Write the regenerated file into the source tree (local dev only — callers gate). */
export function writeKnowledgeBase(cards: AiSuiteKnowledgeCard[]): void {
  writeFileSync(KB_FILE_PATH, serializeKnowledgeBase(cards), "utf8");
}
