// GENERATED by scripts/gen-api-dispatch.mjs — do not edit. Run `node scripts/gen-api-dispatch.mjs --write`.
// One route for every endpoint under /api/sub-accounts/[id]/media-library; handlers live in ../_routes/.
import "server-only";

import { createApiDispatcher } from "@/lib/server/api-dispatch";
import * as h0 from "@/app/api/sub-accounts/[id]/media-library/_routes/[assetId]/public-image/route";
import * as h1 from "@/app/api/sub-accounts/[id]/media-library/_routes/[assetId]/refresh/route";
import * as h2 from "@/app/api/sub-accounts/[id]/media-library/_routes/[assetId]/route";
import * as h3 from "@/app/api/sub-accounts/[id]/media-library/_routes/[assetId]/share/route";
import * as h4 from "@/app/api/sub-accounts/[id]/media-library/_routes/[assetId]/url/route";
import * as h5 from "@/app/api/sub-accounts/[id]/media-library/_routes/route";
import * as h6 from "@/app/api/sub-accounts/[id]/media-library/_routes/uploads/[intakeId]/complete/route";
import * as h7 from "@/app/api/sub-accounts/[id]/media-library/_routes/uploads/route";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const d = createApiDispatcher([
  ["[assetId]/public-image", h0],
  ["[assetId]/refresh", h1],
  ["[assetId]", h2],
  ["[assetId]/share", h3],
  ["[assetId]/url", h4],
  ["", h5],
  ["uploads/[intakeId]/complete", h6],
  ["uploads", h7],
]);

export const GET = d.GET;
export const HEAD = d.HEAD;
export const POST = d.POST;
export const PUT = d.PUT;
export const PATCH = d.PATCH;
export const DELETE = d.DELETE;
export const OPTIONS = d.OPTIONS;
