import "server-only";

import { NextResponse } from "next/server";

/**
 * Consolidated API route groups (Vercel route-limit fix, 2026-09-29).
 *
 * Vercel caps a deployment at 2,048 routes and every DYNAMIC Next.js route
 * costs three of them (plain, `.rsc`, `_next/data`). A group of related API
 * endpoints is therefore served by ONE optional catch-all route
 * (`<group>/[[...path]]/route.ts`, generated by `scripts/gen-api-dispatch.mjs`)
 * that dispatches to the group's original, unchanged handler modules kept in
 * `<group>/_routes/**` (a private folder Next never routes).
 *
 * Behaviour matches Next's own routing for these handlers:
 *  - URLs and params are unchanged; handlers receive the same
 *    `{ params: Promise<{...}> }` shape (parent params + their own).
 *  - Precedence follows Next: static segment > dynamic > catch-all >
 *    optional catch-all, compared segment by segment.
 *  - No matching path → 404. Path matches but method not exported → 405
 *    with `Allow`. HEAD falls back to GET (body dropped) and OPTIONS to a
 *    204 with `Allow`, as Next does automatically for route handlers.
 */

export type HttpMethod = "GET" | "HEAD" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS";
const METHODS: HttpMethod[] = ["GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"];

type Params = Record<string, string | string[]>;
// Handlers keep their own precise `ctx` types; the dispatcher only guarantees the shape.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Handler = (request: any, context: { params: Promise<any> }) => Response | Promise<Response>;
export type RouteModule = Partial<Record<HttpMethod, Handler>>;

type Segment =
  | { kind: "static"; value: string }
  | { kind: "dynamic"; name: string }
  | { kind: "catchall"; name: string }
  | { kind: "optional"; name: string };

interface CompiledRoute {
  pattern: string;
  segments: Segment[];
  module: RouteModule;
}

const RANK: Record<Segment["kind"], number> = { static: 0, dynamic: 1, catchall: 2, optional: 3 };

function parsePattern(pattern: string): Segment[] {
  return pattern
    .split("/")
    .filter(Boolean)
    .map((s): Segment => {
      let m = /^\[\[\.\.\.([^\]]+)\]\]$/.exec(s);
      if (m) return { kind: "optional", name: m[1] };
      m = /^\[\.\.\.([^\]]+)\]$/.exec(s);
      if (m) return { kind: "catchall", name: m[1] };
      m = /^\[([^\]]+)\]$/.exec(s);
      if (m) return { kind: "dynamic", name: m[1] };
      return { kind: "static", value: s };
    });
}

/** Negative when `a` is more specific than `b` (Next's ordering). */
function compareSpecificity(a: Segment[], b: Segment[]): number {
  const n = Math.max(a.length, b.length);
  for (let i = 0; i < n; i += 1) {
    const x = a[i];
    const y = b[i];
    // Only an optional catch-all can match the same path as a shorter
    // pattern (`a` vs `a/[[...x]]`); the exact, shorter one wins, as in Next.
    if (!x) return -1;
    if (!y) return 1;
    if (RANK[x.kind] !== RANK[y.kind]) return RANK[x.kind] - RANK[y.kind];
  }
  return 0;
}

function matchSegments(segments: Segment[], path: string[]): Params | null {
  const params: Params = {};
  for (let i = 0; i < segments.length; i += 1) {
    const seg = segments[i];
    if (seg.kind === "catchall" || seg.kind === "optional") {
      const rest = path.slice(i);
      if (seg.kind === "catchall" && rest.length === 0) return null;
      if (rest.length) params[seg.name] = rest;
      return params;
    }
    const part = path[i];
    if (part === undefined) return null;
    if (seg.kind === "static") {
      if (seg.value !== part) return null;
    } else {
      params[seg.name] = part;
    }
  }
  return segments.length === path.length ? params : null;
}

function allowedMethods(module: RouteModule): string {
  const set = new Set(METHODS.filter((m) => typeof module[m] === "function"));
  if (set.has("GET")) set.add("HEAD");
  set.add("OPTIONS");
  return METHODS.filter((m) => set.has(m)).join(", ");
}

export function createApiDispatcher(table: Array<[pattern: string, module: unknown]>) {
  const routes: CompiledRoute[] = table
    .map(([pattern, module]) => ({ pattern, segments: parsePattern(pattern), module: module as RouteModule }))
    .sort((a, b) => compareSpecificity(a.segments, b.segments));

  function resolve(path: string[]): { route: CompiledRoute; params: Params } | null {
    for (const route of routes) {
      const params = matchSegments(route.segments, path);
      if (params) return { route, params };
    }
    return null;
  }

  async function dispatch(method: HttpMethod, request: Request, context: { params: Promise<Params> }) {
    const { path, ...parent } = (await context.params) ?? {};
    const segments = Array.isArray(path) ? path : typeof path === "string" ? [path] : [];
    const hit = resolve(segments);
    if (!hit) return NextResponse.json({ error: "Not found" }, { status: 404 });
    const { route, params } = hit;
    const ctx = { params: Promise.resolve({ ...parent, ...params }) };
    const handler = route.module[method];
    if (handler) return handler(request, ctx);
    if (method === "HEAD" && route.module.GET) {
      const res = await route.module.GET(request, ctx);
      return new Response(null, { status: res.status, statusText: res.statusText, headers: res.headers });
    }
    const allow = allowedMethods(route.module);
    if (method === "OPTIONS") return new Response(null, { status: 204, headers: { Allow: allow } });
    return new Response(null, { status: 405, headers: { Allow: allow } });
  }

  const bind = (method: HttpMethod) => (request: Request, context: { params: Promise<Params> }) =>
    dispatch(method, request, context);

  return {
    GET: bind("GET"),
    HEAD: bind("HEAD"),
    POST: bind("POST"),
    PUT: bind("PUT"),
    PATCH: bind("PATCH"),
    DELETE: bind("DELETE"),
    OPTIONS: bind("OPTIONS"),
    /** For the route-compatibility checks. */
    patterns: routes.map((r) => r.pattern),
  };
}
