import "server-only";

import { getAdminDb } from "@/lib/firebase/admin";
import {
  communityGroupsRoot,
  type CommunityOwnerScope,
} from "@/lib/server/community-scope";

/**
 * Community Shared Architecture Phase 2 (2026-09-19) — the normalized,
 * scoring-purpose read model for "every active participant in this
 * Community, with the points/level/display fields the Leaderboard,
 * reward-eligibility, and Points Overview active-member-count all
 * independently re-derived before this phase (three separate hand-rolled
 * reads of the same underlying active-membership set).
 *
 * Deliberately NOT a replacement for the richer per-scope directory reads
 * (`listMemberDirectory` — tenant, handle/bio/last-seen/banned rows;
 * `listAgencyGroupMembers` — Agency roster management) — those stay
 * exactly as they are, untouched by this phase, since they serve member-
 * management UI that needs fields (handle, bio, invite/pending/removed
 * states) this scoring-only shape has no reason to carry. This is the
 * leaner "who's an active, scoreable participant, and what are their
 * points/level/name" read used by Leaderboard/Rewards/Points Overview.
 *
 * Tenant: joins `communityGroups/{groupId}/memberships` (points/level/
 * status live here — see `GroupMembership`'s own doc comment) with
 * `subAccounts/{id}/members` (display name/avatar live here) — the same
 * two-doc join `listMemberDirectory`/`getLeaderboard` already performed
 * before this phase. The membership doc's own id IS the memberId
 * (every write site does `.collection("memberships").doc(memberId)` —
 * confirmed by inspection, never a separate autogenerated id), so no
 * extra field read is needed to recover it.
 *
 * Agency: reads the roster doc directly — it already carries
 * displayName/points/level itself (see `AgencyGroupMemberRoster`'s own
 * doc comment, community-agency-service.ts), no second doc to join.
 */
export interface CommunityParticipant {
  /** The doc that actually holds `points`/`level` for this participant —
   *  a tenant membership doc id (== memberId) or an Agency roster doc id. */
  id: string;
  displayName: string;
  avatarUrl: string | null;
  points: number;
  level: number;
}

function displayNameFor(
  m: { displayName?: string | null; email?: string } | undefined
): string {
  if (!m) return "Former member";
  if (m.displayName && m.displayName.trim()) return m.displayName.trim();
  return (m.email ?? "").split("@")[0] || "Member";
}

export async function listActiveParticipantsByScope(
  scope: CommunityOwnerScope,
  groupId: string
): Promise<CommunityParticipant[]> {
  const db = getAdminDb();

  if (scope.kind === "agency") {
    const snap = await db
      .collection(`${communityGroupsRoot(scope)}/${groupId}/members`)
      .where("status", "==", "active")
      .get();
    return snap.docs.map((d) => {
      const data = d.data() as {
        displayName?: string;
        email?: string;
        points?: number;
        level?: number;
      };
      return {
        id: d.id,
        displayName: displayNameFor(data),
        avatarUrl: null,
        points: data.points ?? 0,
        level: data.level ?? 1,
      };
    });
  }

  const membershipsSnap = await db
    .collection(`${communityGroupsRoot(scope)}/${groupId}/memberships`)
    .where("status", "==", "active")
    .get();
  const memberIds = membershipsSnap.docs.map((d) => d.id);
  const memberSnaps = memberIds.length
    ? await db.getAll(
        ...memberIds.map((id) =>
          db.doc(`subAccounts/${scope.subAccountId}/members/${id}`)
        )
      )
    : [];
  const memberById = new Map<
    string,
    | { displayName?: string; email?: string; avatarUrl?: string | null }
    | undefined
  >();
  memberIds.forEach((id, i) =>
    memberById.set(
      id,
      memberSnaps[i]?.data() as
        | { displayName?: string; email?: string; avatarUrl?: string | null }
        | undefined
    )
  );

  return membershipsSnap.docs.map((d) => {
    const data = d.data() as { points?: number; level?: number };
    const member = memberById.get(d.id);
    return {
      id: d.id,
      displayName: displayNameFor(member),
      avatarUrl: member?.avatarUrl ?? null,
      points: data.points ?? 0,
      level: data.level ?? 1,
    };
  });
}

/** Cheaper than fetching every doc when only a count is needed — same
 *  active-status filter as `listActiveParticipantsByScope`. */
export async function getActiveParticipantCountByScope(
  scope: CommunityOwnerScope,
  groupId: string
): Promise<number> {
  const db = getAdminDb();
  const col =
    scope.kind === "agency"
      ? db.collection(`${communityGroupsRoot(scope)}/${groupId}/members`)
      : db.collection(`${communityGroupsRoot(scope)}/${groupId}/memberships`);
  const snap = await col.where("status", "==", "active").count().get();
  return snap.data().count;
}
