import "server-only";

import { FieldValue } from "firebase-admin/firestore";
import { getAdminDb } from "@/lib/firebase/admin";
import { getReportDesign } from "@/lib/server/report-design-service";
import { getReadingById } from "@/lib/server/energetic-decoder-service";
import { evaluateChartRule, type ChartRuleReadingInput } from "@/lib/energetics/chart-rules";
import { resolveShortcodes, type ShortcodeReadingInput } from "@/lib/energetics/shortcodes";
import type { ReportPage } from "@/types/report-blocks";
import type { GeneratedReport, GeneratedReportChartStyles } from "@/types/generated-report";
import type { EnergeticDecoderReading } from "@/types/energetic-decoder";
import type { ChartDesign } from "@/types/chart-design";
import { resolveChartDesignsForReading } from "@/lib/server/chart-design-service";

/**
 * Generated Reports — Phase 2 Build Plan Task 2 (2026-08-12), data layer
 * only. Flat top-level collection, same convention as `reportDesigns`/
 * `energeticDecoderReadings` (subAccountId/agencyId fields rather than
 * nested under the sub-account doc). No UI calls `createGeneratedReport`
 * yet — that's the later "Generate Report" task in the Build Plan's
 * sequence; this task is just the record + the real, testable logic that
 * produces it.
 */

function col() {
  return getAdminDb().collection("generatedReports");
}

/** Same fix/reasoning as report-design-service.ts's toIsoString. */
function toIsoString(value: unknown): string | null {
  if (value && typeof value === "object" && "toDate" in value && typeof (value as { toDate: unknown }).toDate === "function") {
    return (value as FirebaseFirestore.Timestamp).toDate().toISOString();
  }
  return null;
}

function toGeneratedReport(id: string, data: FirebaseFirestore.DocumentData): GeneratedReport {
  return {
    id,
    ...(data as Omit<GeneratedReport, "id">),
    generatedAt: toIsoString(data.generatedAt),
  };
}

export async function listGeneratedReports(
  subAccountId: string,
  opts?: { readingId?: string; reportDesignId?: string },
): Promise<GeneratedReport[]> {
  let q: FirebaseFirestore.Query = col().where("subAccountId", "==", subAccountId);
  if (opts?.readingId) q = q.where("readingId", "==", opts.readingId);
  if (opts?.reportDesignId) q = q.where("reportDesignId", "==", opts.reportDesignId);
  const snap = await q.get();
  return snap.docs.map((d) => toGeneratedReport(d.id, d.data()));
}

/**
 * Reading workspace → Reports tab (2026-10-07) — every generated report for
 * one Energetic Profile, across all of its readings (a report always hangs
 * off one reading; older reports keep pointing at the reading they were
 * generated from). Resolves the Profile's reading ids with the same
 * equality-only query the Profile delete guard uses, then reuses
 * listGeneratedReports per reading — no new index, and a report can only
 * appear here if its reading belongs to this Profile in this sub-account.
 */
export async function listGeneratedReportsForProfile(
  subAccountId: string,
  profileId: string,
): Promise<GeneratedReport[]> {
  const readingsSnap = await getAdminDb()
    .collection("energeticDecoderReadings")
    .where("subAccountId", "==", subAccountId)
    .where("profileId", "==", profileId)
    .select()
    .get();
  const perReading = await Promise.all(
    readingsSnap.docs.map((d) => listGeneratedReports(subAccountId, { readingId: d.id })),
  );
  return perReading.flat();
}

export async function getGeneratedReport(subAccountId: string, id: string): Promise<GeneratedReport | null> {
  const snap = await col().doc(id).get();
  if (!snap.exists || snap.data()?.subAccountId !== subAccountId) return null;
  return toGeneratedReport(snap.id, snap.data()!);
}

/**
 * Lifecycle completeness pass (2026-08-12) — the record + Preview/PDF/list
 * existed, but nothing let a practitioner remove one they generated by
 * mistake (regression testing itself had to fall back to a one-off admin
 * script). Deletes ONLY this GeneratedReport document — the source Reading,
 * its Contact, and the ReportDesign it was generated from are untouched,
 * same as deleteReportDesign's own scope on its own record.
 */
export async function deleteGeneratedReport(subAccountId: string, id: string): Promise<void> {
  const ref = col().doc(id);
  const snap = await ref.get();
  if (!snap.exists || snap.data()?.subAccountId !== subAccountId) throw new Error("Generated report not found");
  await ref.delete();
}

/**
 * The actual snapshot logic — filters pages by `visibleIf` and resolves
 * shortcodes exactly the way `ReportDesignViewer` renders them live,
 * against one specific reading, once, at generation time.
 */
function resolveSnapshotPages(pages: ReportPage[], ruleInput: ChartRuleReadingInput, shortcodeInput: ShortcodeReadingInput): ReportPage[] {
  const visiblePages = pages.filter((p) => !p.visibleIf || evaluateChartRule(p.visibleIf, ruleInput));
  return visiblePages.map((p) => ({
    ...p,
    blocks: p.blocks.map((b) => (b.type === "text" ? { ...b, html: resolveShortcodes(b.html, shortcodeInput) } : b)),
    elements: p.elements?.map((e) => ({
      ...e,
      payload: e.type === "text" ? { ...e.payload, text: resolveShortcodes(String(e.payload.text ?? ""), shortcodeInput) } : e.type === "shortcode" ? { ...e.payload, resolvedText: resolveShortcodes(`{{${String(e.payload.token ?? "full_name")}}}`, shortcodeInput) } : e.payload,
    })),
  }));
}

export async function createGeneratedReport(opts: {
  agencyId: string;
  subAccountId: string;
  reportDesignId: string;
  readingId: string;
  generatedByUid: string;
}): Promise<GeneratedReport | { error: string }> {
  const [design, reading] = await Promise.all([
    getReportDesign(opts.subAccountId, opts.reportDesignId),
    getReadingById(opts.subAccountId, opts.readingId),
  ]);
  if (!design) return { error: "Report design not found" };
  if (!reading) return { error: "Reading not found" };

  const ruleInput: ChartRuleReadingInput = { humanDesign: reading.humanDesign, astrology: reading.astrology };
  const shortcodeInput: ShortcodeReadingInput = {
    name: reading.name,
    birthDate: reading.birthDate,
    birthPlace: reading.birthPlace,
    humanDesign: reading.humanDesign,
    astrology: reading.astrology,
    spheres: reading.spheres,
  };

  const doc = {
    subAccountId: opts.subAccountId,
    agencyId: opts.agencyId,
    reportDesignId: opts.reportDesignId,
    reportDesignTitleAtGeneration: design.title,
    readingId: opts.readingId,
    contactId: reading.contactId ?? null,
    // Phase 3 Task 7 (2026-08-13) — the Reading already carries the
    // correct profileId (Task 2/3/4/5); just copy it, no second lookup.
    profileId: reading.profileId ?? null,
    generatedBy: opts.generatedByUid,
    snapshot: {
      pages: resolveSnapshotPages(design.pages, ruleInput, shortcodeInput),
      layoutVersion: design.layoutVersion ?? 1,
      contentSetId: design.contentSetId ?? null,
      // Unified Chart Designs (2026-10): the chart styling is frozen with
      // the report too, so a later edit to a Chart Design can't change a
      // report that was already generated.
      chartStyles: await captureReportChartStyles(opts.subAccountId, reading),
    },
    generatedAt: FieldValue.serverTimestamp(),
  };
  const ref = await col().add(doc);
  return toGeneratedReport(ref.id, doc);
}

/**
 * Plain copies of the designs a reading resolves to right now (same shared
 * resolver every chart surface uses), for freezing into a report.
 */
async function captureReportChartStyles(
  subAccountId: string,
  reading: Pick<EnergeticDecoderReading, "profileId" | "humanDesign" | "astrology">,
): Promise<GeneratedReportChartStyles> {
  const resolved = await resolveChartDesignsForReading(subAccountId, reading);
  return {
    source: "generation",
    frozenAt: new Date().toISOString(),
    setId: resolved.setId,
    setName: resolved.setName,
    humanDesign: resolved.hdDesign,
    mandala: resolved.mandalaDesign,
    astrology: resolved.astroDesign,
    frequency: null,
  };
}

/**
 * The chart designs a generated report renders with: its frozen styling
 * when it has one, otherwise (reports generated before styling was frozen,
 * not yet covered by the freeze script) the reading's current designs —
 * exactly how those reports have always rendered.
 */
export async function chartDesignsForGeneratedReport(
  subAccountId: string,
  report: Pick<GeneratedReport, "snapshot">,
  reading: Pick<EnergeticDecoderReading, "profileId" | "humanDesign" | "astrology">,
): Promise<{
  hdDesign: ChartDesign | null;
  mandalaDesign: ChartDesign | null;
  astroDesign: ChartDesign | null;
  frozen: boolean;
}> {
  const frozen = report.snapshot?.chartStyles;
  if (frozen) {
    return {
      hdDesign: frozen.humanDesign ?? null,
      mandalaDesign: frozen.mandala ?? null,
      astroDesign: frozen.astrology ?? null,
      frozen: true,
    };
  }
  const { hdDesign, mandalaDesign, astroDesign } = await resolveChartDesignsForReading(subAccountId, reading);
  return { hdDesign, mandalaDesign, astroDesign, frozen: false };
}
