// GENERATED by scripts/gen-api-dispatch.mjs — do not edit. Run `node scripts/gen-api-dispatch.mjs --write`.
// One route for every endpoint under /api/sub-accounts/[id]/routines; handlers live in ../_routes/.
import "server-only";

import { createApiDispatcher } from "@/lib/server/api-dispatch";
import * as h0 from "@/app/api/sub-accounts/[id]/routines/_routes/[routineId]/complete/route";
import * as h1 from "@/app/api/sub-accounts/[id]/routines/_routes/[routineId]/history/route";
import * as h2 from "@/app/api/sub-accounts/[id]/routines/_routes/[routineId]/route";
import * as h3 from "@/app/api/sub-accounts/[id]/routines/_routes/activities/route";
import * as h4 from "@/app/api/sub-accounts/[id]/routines/_routes/calendar/route";
import * as h5 from "@/app/api/sub-accounts/[id]/routines/_routes/route";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const d = createApiDispatcher([
  ["[routineId]/complete", h0],
  ["[routineId]/history", h1],
  ["[routineId]", h2],
  ["activities", h3],
  ["calendar", h4],
  ["", h5],
]);

export const GET = d.GET;
export const HEAD = d.HEAD;
export const POST = d.POST;
export const PUT = d.PUT;
export const PATCH = d.PATCH;
export const DELETE = d.DELETE;
export const OPTIONS = d.OPTIONS;
