"use client";

import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Facebook, Instagram } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { SocialPostDoc, SocialPostStatus } from "@/types/social";

function toDate(v: unknown): Date | null { if (!v) return null; if (v instanceof Date) return v; const candidate = v as { toDate?: () => Date; seconds?: number }; if (typeof candidate.toDate === "function") return candidate.toDate(); return typeof candidate.seconds === "number" ? new Date(candidate.seconds * 1000) : null; }
const WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const STATUS_DOT: Record<SocialPostStatus, string> = { draft: "bg-zinc-400", scheduled: "bg-blue-500", publishing: "bg-amber-500", published: "bg-emerald-500", failed: "bg-red-500" };

export function SocialContentCalendar({ posts, view, onSelectPost }: { posts: SocialPostDoc[]; view: "month" | "week" | "list"; onSelectPost?: (post: SocialPostDoc) => void }) {
  const [cursor, setCursor] = useState(() => { const now = new Date(); return new Date(now.getFullYear(), now.getMonth(), 1); });
  const today = new Date();
  const year = cursor.getFullYear(); const month = cursor.getMonth();
  const byDay = useMemo(() => { const map = new Map<string, SocialPostDoc[]>(); posts.forEach((post) => { const date = toDate(post.scheduledAt); if (!date) return; const key = `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`; map.set(key, [...(map.get(key) ?? []), post]); }); return map; }, [posts]);
  const monthLabel = cursor.toLocaleDateString(undefined, { month: "long", year: "numeric" });
  const first = new Date(year, month, 1); const lead = (first.getDay() + 6) % 7; const days = new Date(year, month + 1, 0).getDate();
  const cells: (number | null)[] = [...Array.from({ length: lead }, () => null), ...Array.from({ length: days }, (_, index) => index + 1)]; while (cells.length % 7) cells.push(null);
  const chip = (post: SocialPostDoc) => <button key={post.id} type="button" onClick={() => onSelectPost?.(post)} className="flex w-full items-center gap-1 rounded-lg border bg-white px-2 py-1.5 text-left text-[11px] shadow-sm transition hover:border-primary dark:bg-card" title={post.caption || "Untitled post"}><span className={cn("h-1.5 w-1.5 shrink-0 rounded-full", STATUS_DOT[post.status])} />{post.targets.includes("facebook") && <Facebook className="h-3 w-3 text-blue-500" />}{post.targets.includes("instagram") && <Instagram className="h-3 w-3 text-pink-500" />}<span className="truncate">{post.caption || "Untitled post"}</span></button>;
  return <div className="rounded-2xl border bg-white shadow-sm dark:bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-4 py-3"><div className="flex items-center gap-2"><Button type="button" variant="outline" size="sm" onClick={() => setCursor(new Date(year, month - 1, 1))} aria-label="Previous month"><ChevronLeft className="h-4 w-4" /></Button><Button type="button" variant="outline" size="sm" onClick={() => setCursor(new Date(today.getFullYear(), today.getMonth(), 1))}>Today</Button><Button type="button" variant="outline" size="sm" onClick={() => setCursor(new Date(year, month + 1, 1))} aria-label="Next month"><ChevronRight className="h-4 w-4" /></Button><h2 className="ml-2 text-sm font-semibold">{monthLabel}</h2></div><span className="text-xs text-muted-foreground">{posts.length} matching post{posts.length === 1 ? "" : "s"}</span></div>{view === "list" ? <div className="divide-y">{posts.length === 0 ? <p className="p-8 text-center text-sm text-muted-foreground">No scheduled posts in this view.</p> : posts.map((post) => <div key={post.id} className="flex items-center gap-3 p-4">{chip(post)}<span className="ml-auto text-xs text-muted-foreground">{toDate(post.scheduledAt)?.toLocaleString()}</span></div>)}</div> : view === "week" ? <div className="grid gap-3 p-4 sm:grid-cols-7">{Array.from({ length: 7 }, (_, index) => { const date = new Date(year, month, Math.min(days, 1 + index)); const key = `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`; return <div key={index} className="min-h-32 rounded-xl border p-2"><p className="mb-2 text-xs font-semibold text-muted-foreground">{WEEKDAYS[index]} {date.getDate()}</p><div className="space-y-1">{(byDay.get(key) ?? []).map(chip)}</div></div>; })}</div> : <><div className="grid grid-cols-7 border-b text-center text-[11px] font-medium text-muted-foreground">{WEEKDAYS.map((day) => <div key={day} className="py-2">{day}</div>)}</div><div className="grid grid-cols-7">{cells.map((day, index) => { const key = day == null ? `blank-${index}` : `${year}-${month}-${day}`; return <div key={key} className={cn("min-h-[112px] border-b border-r p-2 [&:nth-child(7n)]:border-r-0", day == null && "bg-muted/20")}>{day != null && <><div className={cn("mb-2 inline-flex h-6 w-6 items-center justify-center rounded-full text-xs", today.getFullYear() === year && today.getMonth() === month && today.getDate() === day ? "bg-primary font-semibold text-primary-foreground" : "text-muted-foreground")}>{day}</div><div className="space-y-1">{(byDay.get(key) ?? []).map(chip)}</div></>}</div>; })}</div></>}</div>;
}
