"use client";

import { useState } from "react";
import { MoreHorizontal, Plus, Search, Sparkles } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const rows = [
  ["Your Energetic Blueprint", "Draft", "Default", "4", "Just now"],
  ["Business & Career Report", "Active", "Owner Review — Blank Frequency", "3", "2 days ago"],
  ["Midnight Dunes", "Draft", "Default", "5", "Aug 12, 2026"],
];

export function ReportDesignReviewIndex() {
  const [open, setOpen] = useState(false);
  return <section className="mx-auto mb-5 w-full max-w-[1400px] rounded-3xl border border-violet-100 bg-white p-5 shadow-sm">
    <div className="relative overflow-hidden rounded-2xl bg-[linear-gradient(105deg,#fff 0%,#fbf7ff 58%,#f0e6ff 100%)] p-5"><div className="absolute -right-8 -top-16 h-40 w-40 rounded-full bg-[radial-gradient(circle_at_35%_35%,#fff3cf,transparent_12%),radial-gradient(circle,#e5d4ff,transparent_68%)]" /><div className="relative flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-violet-700"><Sparkles className="h-5 w-5" /><span className="text-sm font-semibold">Energetic Decoder · Report Builder</span></div><h2 className="mt-2 font-serif text-3xl font-semibold tracking-tight text-[#18204a]">Report Designs</h2><p className="mt-1 text-sm text-muted-foreground">Build polished, multi-page reports on a freeform canvas.</p></div><button type="button" onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#5420a8] px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> Create report design</button></div></div>
    <div className="mt-4 flex flex-wrap gap-2"><label className="relative min-w-[230px] flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input placeholder="Search report designs…" className="h-10 w-full rounded-lg border pl-9 pr-3 text-sm outline-none focus:border-violet-400" /></label><select className="h-10 rounded-lg border bg-white px-3 text-sm"><option>All statuses</option><option>Draft</option><option>Active</option></select></div>
    <div className="mt-3 overflow-x-auto rounded-2xl border border-violet-100"><div className="min-w-[760px]"><div className="grid grid-cols-[minmax(220px,1.5fr)_110px_180px_80px_120px_60px] gap-3 bg-[#f7f2ff] px-4 py-3 text-xs font-semibold uppercase tracking-wide text-violet-800"><span>Name</span><span>Status</span><span>Content Set</span><span>Pages</span><span>Updated</span><span>Actions</span></div>{rows.map((row) => <div key={row[0]} className="grid grid-cols-[minmax(220px,1.5fr)_110px_180px_80px_120px_60px] items-center gap-3 border-t px-4 py-3 text-sm"><span className="font-medium text-[#18204a]">{row[0]}</span><span className={`w-fit rounded-full px-2 py-1 text-xs ${row[1] === "Active" ? "bg-emerald-50 text-emerald-700" : "bg-violet-100 text-violet-800"}`}>{row[1]}</span><span className="truncate text-muted-foreground">{row[2]}</span><span>{row[3]}</span><span className="text-xs text-muted-foreground">{row[4]}</span><button type="button" className="rounded-lg p-2 hover:bg-violet-50" aria-label="More actions"><MoreHorizontal className="h-4 w-4" /></button></div>)}</div></div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle className="font-serif text-2xl">New Report Design</DialogTitle></DialogHeader><div className="space-y-4"><label className="block text-sm font-medium">Report Design name<input className="mt-1.5 h-10 w-full rounded-lg border px-3" placeholder="e.g. Energetic Blueprint" /></label><label className="block text-sm font-medium">Content Set<select className="mt-1.5 h-10 w-full rounded-lg border bg-white px-3"><option>Default (built-in)</option><option>Owner Review — Blank Frequency</option></select></label><fieldset className="space-y-2"><legend className="text-sm font-medium">Start from</legend><div className="grid grid-cols-2 gap-2"><button type="button" className="rounded-xl border border-violet-300 bg-violet-50 p-3 text-left text-sm font-semibold">Blank canvas<span className="mt-1 block text-xs font-normal text-muted-foreground">Start with a clean page</span></button><button type="button" className="rounded-xl border p-3 text-left text-sm font-semibold">Template<span className="mt-1 block text-xs font-normal text-muted-foreground">Choose a Magnetix structure</span></button></div></fieldset><label className="block text-sm font-medium">Page size<select className="mt-1.5 h-10 w-full rounded-lg border bg-white px-3"><option>US Letter</option><option>A4</option><option>Custom</option></select></label><button type="button" onClick={() => setOpen(false)} className="w-full rounded-xl bg-[#5420a8] py-2.5 text-sm font-semibold text-white">Create & open canvas</button></div></DialogContent></Dialog>
  </section>;
}
