// GENERATED by scripts/gen-api-dispatch.mjs — do not edit. Run `node scripts/gen-api-dispatch.mjs --write`.
// One route for every endpoint under /api/sub-accounts/[id]/projects; handlers live in ../_routes/.
import "server-only";

import { createApiDispatcher } from "@/lib/server/api-dispatch";
import * as h0 from "@/app/api/sub-accounts/[id]/projects/_routes/[projectId]/activity/route";
import * as h1 from "@/app/api/sub-accounts/[id]/projects/_routes/[projectId]/milestones/[milestoneId]/route";
import * as h2 from "@/app/api/sub-accounts/[id]/projects/_routes/[projectId]/milestones/route";
import * as h3 from "@/app/api/sub-accounts/[id]/projects/_routes/[projectId]/route";
import * as h4 from "@/app/api/sub-accounts/[id]/projects/_routes/[projectId]/steps/[stepId]/route";
import * as h5 from "@/app/api/sub-accounts/[id]/projects/_routes/[projectId]/steps/route";
import * as h6 from "@/app/api/sub-accounts/[id]/projects/_routes/generate/route";
import * as h7 from "@/app/api/sub-accounts/[id]/projects/_routes/route";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const d = createApiDispatcher([
  ["[projectId]/activity", h0],
  ["[projectId]/milestones/[milestoneId]", h1],
  ["[projectId]/milestones", h2],
  ["[projectId]", h3],
  ["[projectId]/steps/[stepId]", h4],
  ["[projectId]/steps", h5],
  ["generate", h6],
  ["", h7],
]);

export const GET = d.GET;
export const HEAD = d.HEAD;
export const POST = d.POST;
export const PUT = d.PUT;
export const PATCH = d.PATCH;
export const DELETE = d.DELETE;
export const OPTIONS = d.OPTIONS;
