import type { Timestamp, FieldValue } from "firebase/firestore";

/**
 * Quotes — the v1 "Estimate" feature (GHL-equivalent click-to-accept).
 *
 * Lifecycle:
 *   draft → sent → viewed → accepted | declined | expired
 *   accepted → paid (operator marks paid manually; v1 has no payment
 *   collection — payment is handled off-system by the operator).
 *
 * "expired" is a derived status — when `validUntil` is in the past we
 * treat the quote as expired on read regardless of the stored `status`.
 * The stored status only flips to "expired" if the operator explicitly
 * actions it OR a background task sweeps (out of scope for v1; the
 * read-time check covers the visitor-facing public page either way).
 *
 * Tenancy: every quote carries `agencyId / subAccountId / createdByUid`
 * to match the per-sub-account isolation pattern used by contacts /
 * deals / forms / etc. Firestore rules read `subAccountId` to gate.
 *
 * The `publicTokenHash` field stores SHA-256 of the public-share token —
 * never the token itself. The token is only ever revealed in the
 * outbound email URL and verified by HMAC, so an admin DB dump can't
 * leak shareable links.
 */

export type QuoteStatus =
  | "draft"
  | "sent"
  | "viewed"
  | "accepted"
  | "declined"
  | "expired"
  | "paid";

/**
 * What the document is for. `quote` = an estimate the recipient
 * accepts/declines; `invoice` = a demand for payment with a Stripe
 * Payment Link. A doc starts as `quote` (default) or `invoice` (operator
 * skipped the estimate). An accepted quote can be converted to an
 * invoice in place via /convert-to-invoice — `kind` flips and a new
 * invoice number is issued.
 */
export type QuoteKind = "quote" | "invoice";

export interface QuoteLineItem {
  /** Local UUID (client-generated). Not a separate Firestore doc — the
   *  array of items lives inline on the Quote. v1 keeps it simple; we
   *  can split into a subcollection if items ever grow unbounded. */
  id: string;
  description: string;
  /** Allow fractional (e.g. 2.5 hours). Clamped to >= 0 at write time. */
  quantity: number;
  /** In the quote's currency (whole units, not cents). Clamped to >= 0. */
  unitPrice: number;
  /** Back-reference to the source product when this line was added from
   *  the catalog. Null for ad-hoc lines. The snapshot of name/price (in
   *  `description` + `unitPrice`) is authoritative — editing or archiving
   *  the product later never changes this line item. */
  productId?: string | null;
}

/** Global discount applied to the line-item subtotal. */
export type QuoteDiscount =
  | { type: "percent"; value: number } // 0–100
  | { type: "flat"; value: number } // whole units of the quote currency
  | null;

/** A declined-quote reason. The picker on the public page surfaces a
 *  fixed set; the operator sees both the reason and the optional note
 *  the recipient typed. "Other" requires a note. */
export const DECLINE_REASONS = [
  "Too expensive",
  "Not the right fit",
  "Bad timing",
  "Going with a competitor",
  "Other",
] as const;
export type DeclineReason = (typeof DECLINE_REASONS)[number];

export interface Quote {
  id: string;

  // ── Tenancy ───────────────────────────────────────────────────────
  agencyId: string;
  subAccountId: string;
  createdByUid: string;

  // ── Identity ─────────────────────────────────────────────────────
  contactId: string;
  /** Human-readable, year-prefixed sequential. Format `Q-${year}-${nnnn}`
   *  for quotes and `INV-${year}-${nnnn}` for invoices (e.g. `Q-2026-0001`,
   *  `INV-2026-0001`). Generated by lib/quotes/number.ts in an atomic
   *  transaction so two operators issuing simultaneously can't collide.
   *  Per-sub-account sequence; quotes and invoices use SEPARATE counters
   *  so the numbering of each is independent. */
  quoteNumber: string;
  /** Quote vs invoice. Defaults to "quote" on read for docs created
   *  before this field shipped. */
  kind: QuoteKind;

  // ── State ────────────────────────────────────────────────────────
  status: QuoteStatus;

  // ── Money ────────────────────────────────────────────────────────
  /** ISO 4217. Defaults to "USD". */
  currency: string;
  lineItems: QuoteLineItem[];
  /** Applied to the line-item subtotal before tax. */
  globalDiscount: QuoteDiscount;
  /** 0–100. Null = no tax applied. Applied to (subtotal − discount). */
  globalTaxPercent: number | null;

  // ── Recipient-facing content ─────────────────────────────────────
  termsAndNotes: string;
  /** Separate from `contact.company` so the operator can address the
   *  quote to a billing entity that differs from the contact's parent
   *  company (e.g. "ACME Holdings Pty Ltd" vs day-to-day "ACME"). The
   *  recipient sees this on the public page. */
  billedToOrganization: string | null;
  /** Free-form billing/postal address snapshotted from the recipient
   *  contact at the moment the contact is picked. Operator can edit
   *  per-document without affecting the contact's saved address.
   *  Null = none stored; rendered as empty on the document. */
  billingAddress: string | null;
  /** When the quote becomes invalid for acceptance. Null = no expiry.
   *  Past date = read-time treatment as expired regardless of `status`.
   *  Quote-only — ignored for invoices (they don't expire). */
  validUntil: Timestamp | FieldValue | null;
  /** Invoice-only — days from send until payment is due. 0 = "due on
   *  receipt", null = "no specific due date stated". Surfaced as
   *  "Payment due X days after sending" on the invoice email + public
   *  view. v1 doesn't auto-flip status to "overdue"; it's a recipient-
   *  facing label only. */
  paymentDueDays: number | null;

  // ── Behaviour flags ──────────────────────────────────────────────
  /** When true, accepting the quote auto-creates a Deal at the "Won"
   *  stage with the quote total as `value`. Operator can uncheck per
   *  quote for cases where they're already tracking the deal manually. */
  autoCreateDealOnAccept: boolean;

  // ── Lifecycle timestamps ─────────────────────────────────────────
  sentAt: Timestamp | FieldValue | null;
  viewedAt: Timestamp | FieldValue | null;
  acceptedAt: Timestamp | FieldValue | null;
  declinedAt: Timestamp | FieldValue | null;
  declineReason: DeclineReason | null;
  declineNote: string | null;
  paidAt: Timestamp | FieldValue | null;
  /** Stamped when an accepted quote was converted to an invoice. Null on
   *  docs that started life as an invoice or were never converted. */
  convertedFromQuoteAt: Timestamp | FieldValue | null;

  // ── Payment link (invoices only) ─────────────────────────────────
  /** Stripe Payment Link URL — buyer clicks "Pay" on the public invoice
   *  view or email to land here. Cached so re-sending the same invoice
   *  reuses the link. Null when the invoice hasn't been sent yet OR when
   *  the doc is a quote. */
  paymentLinkUrl: string | null;
  /** Stripe Payment Link id (plink_…). Used to deactivate the old link
   *  when the invoice is edited after send and a new link is minted. */
  paymentLinkId: string | null;
  /** When the cached payment link was created. The send route compares
   *  this to `updatedAt` — if the invoice was edited since mint, the
   *  link is deactivated and a fresh one is minted. */
  paymentLinkMintedAt: Timestamp | FieldValue | null;

  // ── Public-share token (hash only — never the raw token) ─────────
  /** SHA-256 hex of the HMAC-signed public token. Used so we can verify
   *  a presented token without needing the token to exist in Firestore.
   *  The raw token is only ever exposed in the outbound email URL. */
  publicTokenHash: string;

  // ── Territory ────────────────────────────────────────────────────
  /** Denormalized territory tag, inherited from the quote's contact at
   *  creation and kept in sync when the contact is re-tagged. `null` on
   *  docs created before territory scoping shipped. Ignored unless the
   *  sub-account's `territoryScopingEnabled` is true. */
  territoryId?: string | null;

  // ── Audit ────────────────────────────────────────────────────────
  createdAt: Timestamp | FieldValue | null;
  updatedAt: Timestamp | FieldValue | null;
}

/** Sensible defaults for a freshly-created quote. The CRUD helper fills
 *  in the missing fields (id, tenancy, contactId, quoteNumber, hash,
 *  timestamps) and merges in any operator-supplied overrides. */
export const DEFAULT_QUOTE: Omit<
  Quote,
  | "id"
  | "agencyId"
  | "subAccountId"
  | "createdByUid"
  | "contactId"
  | "quoteNumber"
  | "publicTokenHash"
  | "createdAt"
  | "updatedAt"
> = {
  kind: "quote",
  status: "draft",
  currency: "USD",
  lineItems: [],
  globalDiscount: null,
  globalTaxPercent: null,
  termsAndNotes: "",
  billedToOrganization: null,
  billingAddress: null,
  validUntil: null,
  paymentDueDays: null,
  autoCreateDealOnAccept: true,
  sentAt: null,
  viewedAt: null,
  acceptedAt: null,
  declinedAt: null,
  declineReason: null,
  declineNote: null,
  paidAt: null,
  convertedFromQuoteAt: null,
  paymentLinkUrl: null,
  paymentLinkId: null,
  paymentLinkMintedAt: null,
};

/** Shape of the JSON payload the public quote page POSTs when the
 *  recipient clicks Accept / Decline. Used by the public API route. */
export interface QuoteRespondPayload {
  action: "accept" | "decline";
  /** Required when action === "decline". */
  reason?: DeclineReason;
  /** Required when reason === "Other". Optional otherwise. */
  note?: string;
}
