// GENERATED by scripts/gen-api-dispatch.mjs — do not edit. Run `node scripts/gen-api-dispatch.mjs --write`.
// One route for every endpoint under /api/sub-accounts/[id]/ytcs; handlers live in ../_routes/.
import "server-only";

import { createApiDispatcher } from "@/lib/server/api-dispatch";
import * as h0 from "@/app/api/sub-accounts/[id]/ytcs/_routes/ideas/[ideaId]/duplicate/route";
import * as h1 from "@/app/api/sub-accounts/[id]/ytcs/_routes/ideas/[ideaId]/route";
import * as h2 from "@/app/api/sub-accounts/[id]/ytcs/_routes/ideas/[ideaId]/turn-into-video/route";
import * as h3 from "@/app/api/sub-accounts/[id]/ytcs/_routes/ideas/route";
import * as h4 from "@/app/api/sub-accounts/[id]/ytcs/_routes/settings/route";
import * as h5 from "@/app/api/sub-accounts/[id]/ytcs/_routes/videos/[videoId]/duplicate/route";
import * as h6 from "@/app/api/sub-accounts/[id]/ytcs/_routes/videos/[videoId]/generate-script-prompt/route";
import * as h7 from "@/app/api/sub-accounts/[id]/ytcs/_routes/videos/[videoId]/generate-title-prompt/route";
import * as h8 from "@/app/api/sub-accounts/[id]/ytcs/_routes/videos/[videoId]/route";
import * as h9 from "@/app/api/sub-accounts/[id]/ytcs/_routes/videos/[videoId]/script-generations/[generationId]/use-as-current/route";
import * as h10 from "@/app/api/sub-accounts/[id]/ytcs/_routes/videos/[videoId]/script-generations/route";
import * as h11 from "@/app/api/sub-accounts/[id]/ytcs/_routes/videos/route";
import * as h12 from "@/app/api/sub-accounts/[id]/ytcs/_routes/voice-notes/route";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const d = createApiDispatcher([
  ["ideas/[ideaId]/duplicate", h0],
  ["ideas/[ideaId]", h1],
  ["ideas/[ideaId]/turn-into-video", h2],
  ["ideas", h3],
  ["settings", h4],
  ["videos/[videoId]/duplicate", h5],
  ["videos/[videoId]/generate-script-prompt", h6],
  ["videos/[videoId]/generate-title-prompt", h7],
  ["videos/[videoId]", h8],
  ["videos/[videoId]/script-generations/[generationId]/use-as-current", h9],
  ["videos/[videoId]/script-generations", h10],
  ["videos", h11],
  ["voice-notes", h12],
]);

export const GET = d.GET;
export const HEAD = d.HEAD;
export const POST = d.POST;
export const PUT = d.PUT;
export const PATCH = d.PATCH;
export const DELETE = d.DELETE;
export const OPTIONS = d.OPTIONS;
