// GENERATED by scripts/gen-api-dispatch.mjs — do not edit. Run `node scripts/gen-api-dispatch.mjs --write`.
// One route for every endpoint under /api/sub-accounts/[id]/growth; handlers live in ../_routes/.
import "server-only";

import { createApiDispatcher } from "@/lib/server/api-dispatch";
import * as h0 from "@/app/api/sub-accounts/[id]/growth/_routes/goals/[goalId]/route";
import * as h1 from "@/app/api/sub-accounts/[id]/growth/_routes/goals/route";
import * as h2 from "@/app/api/sub-accounts/[id]/growth/_routes/money/[entryId]/route";
import * as h3 from "@/app/api/sub-accounts/[id]/growth/_routes/money/route";
import * as h4 from "@/app/api/sub-accounts/[id]/growth/_routes/money/stats/route";
import * as h5 from "@/app/api/sub-accounts/[id]/growth/_routes/pages/[pageId]/route";
import * as h6 from "@/app/api/sub-accounts/[id]/growth/_routes/pages/route";
import * as h7 from "@/app/api/sub-accounts/[id]/growth/_routes/social/[platformId]/logs/route";
import * as h8 from "@/app/api/sub-accounts/[id]/growth/_routes/social/[platformId]/route";
import * as h9 from "@/app/api/sub-accounts/[id]/growth/_routes/social/route";
import * as h10 from "@/app/api/sub-accounts/[id]/growth/_routes/week-stats/route";
import * as h11 from "@/app/api/sub-accounts/[id]/growth/_routes/weekly-review/route";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const d = createApiDispatcher([
  ["goals/[goalId]", h0],
  ["goals", h1],
  ["money/[entryId]", h2],
  ["money", h3],
  ["money/stats", h4],
  ["pages/[pageId]", h5],
  ["pages", h6],
  ["social/[platformId]/logs", h7],
  ["social/[platformId]", h8],
  ["social", h9],
  ["week-stats", h10],
  ["weekly-review", h11],
]);

export const GET = d.GET;
export const HEAD = d.HEAD;
export const POST = d.POST;
export const PUT = d.PUT;
export const PATCH = d.PATCH;
export const DELETE = d.DELETE;
export const OPTIONS = d.OPTIONS;
