// GENERATED by scripts/gen-api-dispatch.mjs — do not edit. Run `node scripts/gen-api-dispatch.mjs --write`.
// One route for every endpoint under /api/community/[saId]/[groupId]; handlers live in ../_routes/.
import "server-only";

import { createApiDispatcher } from "@/lib/server/api-dispatch";
import * as h0 from "@/app/api/community/[saId]/[groupId]/_routes/channels/[channelId]/route";
import * as h1 from "@/app/api/community/[saId]/[groupId]/_routes/channels/route";
import * as h2 from "@/app/api/community/[saId]/[groupId]/_routes/course-picker/route";
import * as h3 from "@/app/api/community/[saId]/[groupId]/_routes/courses/[courseId]/lessons/[lessonId]/complete/route";
import * as h4 from "@/app/api/community/[saId]/[groupId]/_routes/events/[eventId]/join/route";
import * as h5 from "@/app/api/community/[saId]/[groupId]/_routes/events/[eventId]/moderation/route";
import * as h6 from "@/app/api/community/[saId]/[groupId]/_routes/events/route";
import * as h7 from "@/app/api/community/[saId]/[groupId]/_routes/join/route";
import * as h8 from "@/app/api/community/[saId]/[groupId]/_routes/live-rooms/moderation/route";
import * as h9 from "@/app/api/community/[saId]/[groupId]/_routes/live-rooms/route";
import * as h10 from "@/app/api/community/[saId]/[groupId]/_routes/members/[memberId]/route";
import * as h11 from "@/app/api/community/[saId]/[groupId]/_routes/mention-members/route";
import * as h12 from "@/app/api/community/[saId]/[groupId]/_routes/points-rewards/config/route";
import * as h13 from "@/app/api/community/[saId]/[groupId]/_routes/points-rewards/levels/route";
import * as h14 from "@/app/api/community/[saId]/[groupId]/_routes/points-rewards/rewards/[rewardId]/archive/route";
import * as h15 from "@/app/api/community/[saId]/[groupId]/_routes/points-rewards/rewards/[rewardId]/eligible-winners/route";
import * as h16 from "@/app/api/community/[saId]/[groupId]/_routes/points-rewards/rewards/[rewardId]/route";
import * as h17 from "@/app/api/community/[saId]/[groupId]/_routes/points-rewards/rewards/route";
import * as h18 from "@/app/api/community/[saId]/[groupId]/_routes/points-rewards/winners/[winnerId]/route";
import * as h19 from "@/app/api/community/[saId]/[groupId]/_routes/points-rewards/winners/route";
import * as h20 from "@/app/api/community/[saId]/[groupId]/_routes/posts/[postId]/comments/[commentId]/like/route";
import * as h21 from "@/app/api/community/[saId]/[groupId]/_routes/posts/[postId]/comments/[commentId]/route";
import * as h22 from "@/app/api/community/[saId]/[groupId]/_routes/posts/[postId]/comments/route";
import * as h23 from "@/app/api/community/[saId]/[groupId]/_routes/posts/[postId]/course-pins/route";
import * as h24 from "@/app/api/community/[saId]/[groupId]/_routes/posts/[postId]/like/route";
import * as h25 from "@/app/api/community/[saId]/[groupId]/_routes/posts/[postId]/live-watch/route";
import * as h26 from "@/app/api/community/[saId]/[groupId]/_routes/posts/[postId]/poll/vote/route";
import * as h27 from "@/app/api/community/[saId]/[groupId]/_routes/posts/[postId]/replay/route";
import * as h28 from "@/app/api/community/[saId]/[groupId]/_routes/posts/[postId]/route";
import * as h29 from "@/app/api/community/[saId]/[groupId]/_routes/posts/route";
import * as h30 from "@/app/api/community/[saId]/[groupId]/_routes/purchase/route";
import * as h31 from "@/app/api/community/[saId]/[groupId]/_routes/reviews/me/route";
import * as h32 from "@/app/api/community/[saId]/[groupId]/_routes/sections/[sectionId]/route";
import * as h33 from "@/app/api/community/[saId]/[groupId]/_routes/sections/route";
import * as h34 from "@/app/api/community/[saId]/[groupId]/_routes/settings/route";
import * as h35 from "@/app/api/community/[saId]/[groupId]/_routes/settings/upload/route";
import * as h36 from "@/app/api/community/[saId]/[groupId]/_routes/skool-import/disconnect/route";
import * as h37 from "@/app/api/community/[saId]/[groupId]/_routes/skool-import/scan/cancel/route";
import * as h38 from "@/app/api/community/[saId]/[groupId]/_routes/skool-import/scan/retry/route";
import * as h39 from "@/app/api/community/[saId]/[groupId]/_routes/skool-import/scan/start/route";
import * as h40 from "@/app/api/community/[saId]/[groupId]/_routes/skool-import/scan/status/route";
import * as h41 from "@/app/api/community/[saId]/[groupId]/_routes/skool-import/session/[sessionId]/route";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const d = createApiDispatcher([
  ["channels/[channelId]", h0],
  ["channels", h1],
  ["course-picker", h2],
  ["courses/[courseId]/lessons/[lessonId]/complete", h3],
  ["events/[eventId]/join", h4],
  ["events/[eventId]/moderation", h5],
  ["events", h6],
  ["join", h7],
  ["live-rooms/moderation", h8],
  ["live-rooms", h9],
  ["members/[memberId]", h10],
  ["mention-members", h11],
  ["points-rewards/config", h12],
  ["points-rewards/levels", h13],
  ["points-rewards/rewards/[rewardId]/archive", h14],
  ["points-rewards/rewards/[rewardId]/eligible-winners", h15],
  ["points-rewards/rewards/[rewardId]", h16],
  ["points-rewards/rewards", h17],
  ["points-rewards/winners/[winnerId]", h18],
  ["points-rewards/winners", h19],
  ["posts/[postId]/comments/[commentId]/like", h20],
  ["posts/[postId]/comments/[commentId]", h21],
  ["posts/[postId]/comments", h22],
  ["posts/[postId]/course-pins", h23],
  ["posts/[postId]/like", h24],
  ["posts/[postId]/live-watch", h25],
  ["posts/[postId]/poll/vote", h26],
  ["posts/[postId]/replay", h27],
  ["posts/[postId]", h28],
  ["posts", h29],
  ["purchase", h30],
  ["reviews/me", h31],
  ["sections/[sectionId]", h32],
  ["sections", h33],
  ["settings", h34],
  ["settings/upload", h35],
  ["skool-import/disconnect", h36],
  ["skool-import/scan/cancel", h37],
  ["skool-import/scan/retry", h38],
  ["skool-import/scan/start", h39],
  ["skool-import/scan/status", h40],
  ["skool-import/session/[sessionId]", h41],
]);

export const GET = d.GET;
export const HEAD = d.HEAD;
export const POST = d.POST;
export const PUT = d.PUT;
export const PATCH = d.PATCH;
export const DELETE = d.DELETE;
export const OPTIONS = d.OPTIONS;
