"use client";

import { useEffect } from "react";
import { createUsePuck } from "@puckeditor/core";
import { autoWrapNextRootNode } from "@/lib/pages-funnels/puck/auto-hierarchy";

const useTypedPuck = createUsePuck();

/**
 * System B — Auto Hierarchy live controller (master spec §24.1/§6/§11–15).
 * Renders nothing (`null`) — purely a side-effecting watcher, mounted
 * once inside `<Puck>`'s own tree (`editor-shell.tsx`'s `overrides.header`,
 * a sibling of Puck's real header content) specifically so it can use the
 * public `createUsePuck()` hook (same pattern `settings-panel.tsx`/
 * `style-field.tsx` already establish) — Puck's internal `dispatch` is
 * only reachable from inside that provider tree, not from ordinary
 * React state/props passed down from the shell.
 *
 * WHY `dispatch({type:"setData",...})`, not the external `data`/
 * `onChange` prop pair: confirmed by reading the installed
 * `@puckeditor/core@0.23.0` bundle directly — a controlled `<Puck
 * data={data}>`'s `data` prop is captured ONLY ONCE, at mount
 * (`useState(() => ...)`), and Puck never re-reads it on subsequent
 * renders. Calling this shell's own `setData()` from outside would
 * update the value used for autosave/publish but would NOT make Puck's
 * own canvas re-render the corrected tree — a genuine, confirmed
 * divergence risk, not a hypothetical one. `dispatch` is the real,
 * public, documented way to mutate Puck's OWN internal store from
 * outside (`PuckAction`'s `SetDataAction`, `{type:"setData", data:
 * Partial<Data>}` — a first-class, typed action in the installed
 * package, not an internal/undocumented API) — the canvas, Undo/Redo
 * history, and the `onChange` subscription this shell's own `data` state
 * relies on all update consistently from ONE real store mutation.
 *
 * UNDO/REDO (master spec §13/§20 items 42–44): dispatched with
 * `recordHistory: false` — Puck's own history stores full state
 * snapshots per historied action (confirmed: `blendedHistories` /
 * `{state: generatedAppState}` in the installed bundle), not incremental
 * diffs. Since the snapshot for the ORIGINAL insert action is captured
 * BEFORE this un-historied correction runs, pressing Undo once jumps
 * straight back to the pre-drop snapshot — skipping over both the bare
 * insert AND this correction in one step, exactly matching "Undo should
 * remove the entire auto-created wrapper structure generated by that
 * drag." Redo re-applies the NEXT (bare, pre-correction) snapshot
 * forward, which re-triggers this SAME reactive watcher (it watches
 * `appState.data` generally, not just insert actions specifically) and
 * re-applies the correction — this is why the watcher is a continuously
 * reactive effect, not a one-shot `onAction` insert interceptor.
 *
 * SELF-TERMINATING BY CONSTRUCTION: `autoWrapNextRootNode` returns `null`
 * once every root-level node is already a valid container, so the effect
 * naturally stops re-firing once there is nothing left to correct — no
 * separate "already corrected" flag/ref needed, and no infinite loop risk
 * (each correction changes what the NEXT read of `content` looks like,
 * converging in at most `content.length` effect passes).
 */
export function AutoHierarchyWatcher() {
  const data = useTypedPuck((s) => s.appState.data);
  const dispatch = useTypedPuck((s) => s.dispatch);

  useEffect(() => {
    const corrected = autoWrapNextRootNode(data.content);
    if (!corrected) return;
    dispatch({
      type: "setData",
      data: { content: corrected },
      recordHistory: false,
    });
  }, [data, dispatch]);

  return null;
}
