// GENERATED by scripts/gen-api-dispatch.mjs — do not edit. Run `node scripts/gen-api-dispatch.mjs --write`.
// One route for every endpoint under /api/agency/standalone-courses; handlers live in ../_routes/.
import "server-only";

import { createApiDispatcher } from "@/lib/server/api-dispatch";
import * as h0 from "@/app/api/agency/standalone-courses/_routes/[courseId]/community-groups/[groupId]/route";
import * as h1 from "@/app/api/agency/standalone-courses/_routes/[courseId]/community-groups/route";
import * as h2 from "@/app/api/agency/standalone-courses/_routes/[courseId]/complimentary/route";
import * as h3 from "@/app/api/agency/standalone-courses/_routes/[courseId]/lessons/[lessonId]/route";
import * as h4 from "@/app/api/agency/standalone-courses/_routes/[courseId]/lessons/route";
import * as h5 from "@/app/api/agency/standalone-courses/_routes/[courseId]/preview-video/route";
import * as h6 from "@/app/api/agency/standalone-courses/_routes/[courseId]/purchases/route";
import * as h7 from "@/app/api/agency/standalone-courses/_routes/[courseId]/route";
import * as h8 from "@/app/api/agency/standalone-courses/_routes/[courseId]/sections/[sectionId]/route";
import * as h9 from "@/app/api/agency/standalone-courses/_routes/[courseId]/sections/route";
import * as h10 from "@/app/api/agency/standalone-courses/_routes/[courseId]/theme/route";
import * as h11 from "@/app/api/agency/standalone-courses/_routes/[courseId]/upload/route";
import * as h12 from "@/app/api/agency/standalone-courses/_routes/route";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const d = createApiDispatcher([
  ["[courseId]/community-groups/[groupId]", h0],
  ["[courseId]/community-groups", h1],
  ["[courseId]/complimentary", h2],
  ["[courseId]/lessons/[lessonId]", h3],
  ["[courseId]/lessons", h4],
  ["[courseId]/preview-video", h5],
  ["[courseId]/purchases", h6],
  ["[courseId]", h7],
  ["[courseId]/sections/[sectionId]", h8],
  ["[courseId]/sections", h9],
  ["[courseId]/theme", h10],
  ["[courseId]/upload", h11],
  ["", h12],
]);

export const GET = d.GET;
export const HEAD = d.HEAD;
export const POST = d.POST;
export const PUT = d.PUT;
export const PATCH = d.PATCH;
export const DELETE = d.DELETE;
export const OPTIONS = d.OPTIONS;
